Repository Access-projcet/BackEnd, pull requests merged in 2023-04, with the labels that each got.

#4 Refactor : Basic Code Refactoring #1
  src/main/java/com/solver/solver_be/domain/user/controller/UserController.java
  src/main/java/com/solver/solver_be/domain/user/dto/AdminSignupRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/GuestSignupRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/LoginRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/LoginResponseDto.java
  src/main/java/com/solver/solver_be/domain/user/entity/Admin.java
  src/main/java/com/solver/solver_be/domain/user/entity/Guest.java
  src/main/java/com/solver/solver_be/domain/user/entity/UserRoleEnum.java
  src/main/java/com/solver/solver_be/domain/user/repository/AdminRepository.java
  src/main/java/com/solver/solver_be/domain/user/repository/GuestRepository.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/domain/visitform/controller/VisitFormController.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/AccessStatusResponseDto.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/VisitFormResponseDto.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/VisitFormSearchRequestDto.java
  src/main/java/com/solver/solver_be/domain/visitform/entity/VisitForm.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/CustomVisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepositoryCustomImpl.java
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
  src/main/java/com/solver/solver_be/global/response/ResponseCode.java
Labels: bug

#5 Refactor : Basic Code Refactoring #1
  src/main/java/com/solver/solver_be/domain/accessRecord/controller/AccessController.java
  src/main/java/com/solver/solver_be/domain/accessRecord/dto/AccessRecordRequestDto.java
  src/main/java/com/solver/solver_be/domain/accessRecord/entity/AccessRecord.java
  src/main/java/com/solver/solver_be/domain/accessRecord/repository/AccessRecordRepository.java
  src/main/java/com/solver/solver_be/domain/accessRecord/service/AccessService.java
  src/main/java/com/solver/solver_be/domain/company/controller/CompanyController.java
  src/main/java/com/solver/solver_be/domain/company/dto/CompanyRequestDto.java
  src/main/java/com/solver/solver_be/domain/company/dto/CompanyResponseDto.java
  src/main/java/com/solver/solver_be/domain/company/entity/Company.java
  src/main/java/com/solver/solver_be/domain/company/service/CompanyService.java
Labels: bug

#8 Refactor : Access-in 중복 처리 해결 #1
  src/main/java/com/solver/solver_be/domain/access/service/AccessService.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/VisitFormRequestDto.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
Labels: bug

#16 Feat: SSE 기능 구현 #11
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/global/util/sse/controller/NotificationController.java
  src/main/java/com/solver/solver_be/global/util/sse/dto/NotificationResponseDto.java
  src/main/java/com/solver/solver_be/global/util/sse/entity/Notification.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/EmitterRepository.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/NotificationRepository.java
  src/main/java/com/solver/solver_be/global/util/sse/service/NotificationService.java
Labels: enhancement

#19 Refactor : 회사 토큰,이메일 인증 토큰 수정
  src/main/java/com/solver/solver_be/domain/qrCode/entity/QRCode.java
  src/main/java/com/solver/solver_be/global/util/email/controller/EmailController.java
  src/main/java/com/solver/solver_be/global/util/email/dto/EmailRequestDto.java
  src/main/java/com/solver/solver_be/global/util/email/service/EmailService.java
Labels: bug

#22 Refactor : 아이디/비밀번호 찾기 수정 및 비밀번호 변경 기능 구현
  src/main/java/com/solver/solver_be/domain/user/controller/UserController.java
  src/main/java/com/solver/solver_be/domain/user/dto/PasswordChangeRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/domain/user/service/PasswordResetService.java
  src/main/java/com/solver/solver_be/domain/user/service/UserSearchService.java
Labels: bug, enhancement

#26 Refactor : 아이디/비밀번호 찾기 수정
  src/main/java/com/solver/solver_be/domain/user/controller/UserController.java
  src/main/java/com/solver/solver_be/domain/user/controller/UserSearchController.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/domain/user/service/PasswordResetService.java
  src/main/java/com/solver/solver_be/domain/user/service/UserSearchService.java
Labels: bug

#27 Refactor : Basic Code Refactoring #1
  src/main/java/com/solver/solver_be/domain/user/repository/AdminRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
  src/main/java/com/solver/solver_be/global/util/sse/controller/NotificationController.java
  src/main/java/com/solver/solver_be/global/util/sse/entity/Notification.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/EmitterRepository.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/solver/solver_be/global/util/sse/service/NotificationService.java
Labels: enhancement

#29 Feat: 회사 등록시 로비 아이디 생성 #28
  src/main/java/com/solver/solver_be/domain/user/controller/UserController.java
  src/main/java/com/solver/solver_be/domain/user/dto/AdminSignupRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/LobbyRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/entity/Admin.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/global/response/ResponseCode.java
  src/main/java/com/solver/solver_be/global/util/email/service/EmailService.java
Labels: enhancement

#30 Feat: SSE 기능 구현 #11
  src/main/java/com/solver/solver_be/global/util/sse/service/NotificationService.java
Labels: enhancement

#31 Refactor : 회사 등록시 로비 아이디 수정 #1
  src/main/java/com/solver/solver_be/domain/company/entity/Company.java
  src/main/java/com/solver/solver_be/domain/user/dto/LobbyRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
Labels: bug

#32 Feat: SSE 기능 구현 #11
  src/main/java/com/solver/solver_be/global/exception/GlobalExceptionHandler.java
  src/main/java/com/solver/solver_be/global/exception/exceptionType/NotificationException.java
  src/main/java/com/solver/solver_be/global/type/ResponseCode.java
  src/main/java/com/solver/solver_be/global/util/sse/controller/NotificationController.java
  src/main/java/com/solver/solver_be/global/util/sse/dto/NotificationResponseDto.java
  src/main/java/com/solver/solver_be/global/util/sse/entity/Notification.java
  src/main/java/com/solver/solver_be/global/util/sse/repository/NotificationRepository.java
  src/main/java/com/solver/solver_be/global/util/sse/service/NotificationService.java
Labels: enhancement

#33 Refactor : 방문 내역 상태값 숫자 -> 문자로 변경
  src/main/java/com/solver/solver_be/domain/access/service/AccessService.java
  src/main/java/com/solver/solver_be/domain/visitform/entity/VisitForm.java
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
  src/main/java/com/solver/solver_be/global/type/ResponseCode.java
Labels: bug

#37 Refactor : 아이디/비밀번호 찾기 수정
  src/main/java/com/solver/solver_be/domain/company/dto/CompanyRequestDto.java
  src/main/java/com/solver/solver_be/domain/company/dto/CompanyResponseDto.java
  src/main/java/com/solver/solver_be/domain/company/entity/Company.java
  src/main/java/com/solver/solver_be/domain/user/dto/requestDto/AdminSignupRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/requestDto/GuestSignupRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/requestDto/PasswordChangeRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/requestDto/PasswordResetRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/requestDto/UserSearchRequestDto.java
  src/main/java/com/solver/solver_be/domain/user/dto/responseDto/LoginResponseDto.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/global/type/ErrorType.java
  src/main/java/com/solver/solver_be/global/util/email/dto/EmailRequestDto.java
Labels: bug

#38 Refactor : 방문 내역 검색 수정
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
Labels: bug

#39 Refactor : 검색 기능 with QueryDSL
  src/main/java/com/solver/solver_be/domain/visitform/controller/VisitFormController.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/VisitFormPageDto.java
  src/main/java/com/solver/solver_be/domain/visitform/dto/VisitFormSearchRequestDto.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/CustomVisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepository.java
  src/main/java/com/solver/solver_be/domain/visitform/repository/VisitFormRepositoryCustomImpl.java
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
Labels: enhancement

#41 Refactor : JWT 토큰 부분 수정 #1
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/global/security/jwt/JwtAuthFilter.java
  src/main/java/com/solver/solver_be/global/security/jwt/JwtUtil.java
  src/main/java/com/solver/solver_be/global/security/refreshtoken/RefreshToken.java
  src/main/java/com/solver/solver_be/global/security/refreshtoken/RefreshTokenRepository.java
  src/main/java/com/solver/solver_be/global/util/redis/RedisUtil.java
Labels: bug

#42 Refactor : SSE NotificationType Enum 작업 #1
  src/main/java/com/solver/solver_be/domain/visitform/service/VisitFormService.java
  src/main/java/com/solver/solver_be/global/type/NotificationType.java
Labels: enhancement

#44 Refactor : Basic Code Refactoring
  src/main/java/com/solver/solver_be/domain/access/dto/AccessStatusResponseDto.java
  src/main/java/com/solver/solver_be/domain/access/entity/Access.java
  src/main/java/com/solver/solver_be/domain/company/service/CompanyService.java
  src/main/java/com/solver/solver_be/domain/user/service/AdminService.java
  src/main/java/com/solver/solver_be/domain/user/service/GuestService.java
  src/main/java/com/solver/solver_be/global/security/jwt/JwtUtil.java
  src/main/java/com/solver/solver_be/global/security/jwt/dto/TokenDto.java
  src/main/java/com/solver/solver_be/global/security/refreshtoken/RefreshToken.java
  src/main/java/com/solver/solver_be/global/security/refreshtoken/RefreshTokenRepository.java
  src/main/java/com/solver/solver_be/global/type/ErrorType.java
  src/main/java/com/solver/solver_be/global/util/TimeStamped.java
  src/main/java/com/solver/solver_be/global/util/sms/controller/SmsController.java
  src/main/java/com/solver/solver_be/global/util/sms/dto/SmsResponseDto.java
  src/main/java/com/solver/solver_be/global/util/sms/service/SmsService.java
  src/main/java/com/solver/solver_be/global/util/sse/controller/NotificationController.java
  src/main/java/com/solver/solver_be/global/util/sse/entity/NotificationContent.java
  src/main/java/com/solver/solver_be/global/util/sse/service/NotificationService.java
Labels: bug
